spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: toor
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true